services:
  - type: web
    name: hospital-monitor
    runtime: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput --ignore="*.map" || true && python manage.py migrate
    startCommand: daphne -b 0.0.0.0 -p $PORT config.asgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: config.render_settings
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: .onrender.com
    healthCheckPath: /accounts/login/
    autoDeploy: true

databases:
  - name: hospital-db
    databaseName: hospital_monitor
    user: hospital_user
    plan: free
