services:
  - type: web
    name: hospital-monitor
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput --ignore="*.map" || true
      python manage.py migrate --run-syncdb
      python manage.py shell -c "from django.contrib.auth.models import User; User.objects.filter(username='admin').exists() or User.objects.create_superuser('admin','admin@h.ir','admin123')"
    startCommand: daphne -b 0.0.0.0 -p $PORT config.asgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: config.render_settings
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
    autoDeploy: true
